alias p='sudo pacman'
alias t='trizen'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'
alias winetricks32='WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks'
alias steam-wine='wine32 /mnt/extra/extra/wine32/drive_c/Program\ Files/Steam/Steam.exe -no-cef-sandbox'
alias steam-wine64='wine /mnt/extra/extra/wine32/drive_c/Program\ Files/Steam/Steam.exe -no-cef-sandbox'
