alias pup='trizen -Syu'
alias pi='sudo pacman -S'
alias ps='trizen -r'
alias psa='trizen'
alias pr='sudo pacman -R'
alias prd='sudo pacman -Rcc'
alias xi='sudo xbps-install -S'
alias xu='sudo xbps-install -Suv'
alias xr='sudo xbps-remove'
alias xs='xbps-query -Rs'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'
alias winetricks32='WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks'
alias steam-wine='wine32 /mnt/extra/extra/wine32/drive_c/Program\ Files/Steam/Steam.exe -no-cef-sandbox'
alias steam-wine64='wine /mnt/extra/extra/wine32/drive_c/Program\ Files/Steam/Steam.exe -no-cef-sandbox'
