#!/bin/sh

# Configuración

DEV="enp3s0"
RX=`cat /sys/class/net/$DEV/statistics/rx_bytes`
TX=`cat /sys/class/net/$DEV/statistics/tx_bytes`
TIEMPO=`date +%s.%N`

. export_conf

# Íconos

RELOJ="%{T2}%{T-}"
TEMP="%{T2}%{T-}"
MEM="%{T2}%{T-}"
ICPU="%{T2}%{T-}"
VOL="%{T2}%{T-}"
MPD="%{T2}%{T-}"
VOLM="%{T2}%{T-}"
DISCO="%{T2}%{T-}"
REPRODUCIENDO="%{T2}%{T-}"
PAUSADO="%{T2}%{T-}"
DETENIDO="%{T2}%{T-}"
NET_DOWN="%{T2}%{T-}"
NET_UP="%{T2}%{T-}"

# Funciones

calcularColorVol()
{
    if [ $1 -lt $2 ]; then
        echo $RED
    else
        if [ $1 -lt $3 ]; then
            echo $YELLOW
        else
            echo $GREEN
        fi
    fi
}

calcularColor()
{
    if [ $1 -lt $2 ]; then
        echo $GREEN
    else
        if [ $1 -lt $3 ]; then
            echo $YELLOW
        else
            echo $RED
        fi
    fi
}

round()
{
    echo $(printf %.$2f $(echo "scale=$2;(((10^$2)*$1)+0.5)/(10^$2)" | bc))
}

# Barra

sep()
{
    echo -n "%{F$SEP}»%{F-}"
}

cpu()
{
    #CPU=`mpstat | head -n4 | tail -n1 | sed "s/,/./g"| awk '{print 100 - $12}'`
    #CPU=`ps -eo pcpu | awk 'BEGIN {sum=0.0f} {sum+=$1} END {print sum}'`
    #CPU=$(round $CPU 0)
    CPU=`top -bn1 | grep "Cpu(s)" | \
           sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
           awk '{print $1}'`
    COLOR=$(calcularColor $CPU 60 90)
    echo -n "%{A:urxvt -e htop &:}%{F$MAIN}$ICPU %{F$WHITE}CPU: %{F$COLOR}$CPU%%{F-}%{A}"
}

ram()
{
    RAMT=`free | head -n2 | tail -n1 | awk '{print $2}'`
    RAMU=`free | head -n2 | tail -n1 | awk '{print $3}'`
    SWAPT=`free | head -n5 | tail -n1 | awk '{print $2}'`
    SWAPU=`free | head -n5 | tail -n1 | awk '{print $3}'`

    RAM=$(round $((RAMU*100/RAMT)) 0)
    #SWAP=$(round $((SWAPU*100/SWAPT)) 0)

    COLOR_RAM=$(calcularColor $RAM 60 90)
    COLOR_SWAP=$(calcularColor $SWAP 60 90)

    echo -n "%{F$MAIN}$MEM %{F$WHITE}ram:%{F-} %{F$COLOR_RAM}$RAM%%{F-}" #SWAP: %{F$COLOR_SWAP}$SWAP%%{F-}"
}

temp()
{
    CPU0=`sensors | grep "Core 0" | awk '{print $3}' | tr -d '+°C'`
    CPU1=`sensors | grep "Core 2" | awk '{print $3}' | tr -d '+°C'`
    CPU0=$(round $CPU0 0)
    CPU1=$(round $CPU1 0)

    #HDD=`nc localhost 7634 | cut -d '|' -f4`
    #GPU=`nvidia-smi -a | grep "GPU Current Temp" | awk '{print $5}'`
    GPU=`sensors | grep temp1 | tail -1 | awk '{print $2}' | tr -d '+°C'`
    GPU=$(round $GPU 0)

    COLOR_CPU0=$(calcularColor $CPU0 80 90)
    COLOR_CPU1=$(calcularColor $CPU1 80 90)
    COLOR_HDD=$(calcularColor $HDD 50 70)
    COLOR_GPU=$(calcularColor $GPU 90 12li0)

    echo -n "%{F$MAIN}$TEMP %{F$WHITE}cpu0:%{F-} %{F$COLOR_CPU0}$CPU0°C%{F-} \
cpu1: %{F$COLOR_CPU1}$CPU1°C%{F-} \
gpu: %{F$COLOR_GPU}$GPU°C%{F-}"
}

volumen()
{
    MASTER=`amixer get Master | tail -n1 | awk '{print $5}' | tr -d '[%]'`
    ESTADO=`amixer get Master | tail -n1 | awk '{print $6}' | tr -d '[]'`
    if [ $ESTADO == "on" ]; then
        COLOR=$(calcularColorVol $MASTER 10 30 50)
        ICO=$VOL
    else
        COLOR=$RED
        ICO=$VOLM
    fi

    echo "%{A1:pavucontrol &:}%{F$COLOR}$ICO $MASTER%%{F-}%{A}"

}

discos()
{
    ROOT=`df -H | grep sda1 | awk '{print $5}' | tr -d '%'`
    HOME=`df -H | grep sdb7 | awk '{print $5}' | tr -d '%'`

    COLOR_ROOT=$(calcularColor $ROOT 60 90)
    COLOR_HOME=$(calcularColor $HOME 60 90)
    COLOR_INT=$(calcularColor $INT 60 90)

    echo "%{F$MAIN}$DISCO%{F-} /: %{F$COLOR_ROOT}$ROOT% %{F$WHITE}/home: %{F$COLOR_HOME}$HOME%%{F-}"

}

musica()
{
    ESTADO=`mpc | head -n 2 | tail -n 1 | awk '{print $1}'`
    PISTA=`mpc | head -n 1`

    if [ "$ESTADO" == "[playing]" ]; then
        COLOR=$GREEN
        ESTADO=$REPRODUCIENDO
    else
        if [ "$ESTADO" == "[paused]" ]; then
            COLOR=$YELLOW
            ESTADO=$PAUSADO
        else
            COLOR=$RED
            ESTADO=$DETENIDO
        fi
    fi

    echo "%{A1:urxvt -e ncmpcpp -s visualizer &:}%{F$MAIN}$MPD %{F-}mpd%{A}: %{F$COLOR}%{A1:mpc toggle:}$ESTADO%{A}%{F-}"
}

internet()
{
    RXN=`cat /sys/class/net/$DEV/statistics/rx_bytes`
    TXN=`cat /sys/class/net/$DEV/statistics/tx_bytes`
    TIEMPOI=`date +%s.%N`

    DELTA=$(python -c "print(round($TIEMPOI - $TIEMPO,2))")
    RECIBIDO=$(python -c "print(round(($RXN - $RX)/$DELTA/1024))")
    TRANSMITIDO=$(python -c "print(round(($TXN - $TX)/$DELTA/1024))")

    if [ $RECIBIDO -gt 800 ]; then
        RECIBIDO=$(python -c "print(round($RECIBIDO/1024,2))")
        UNIDADRX="MB/s"
    else
        UNIDADRX="kB/s"
    fi

    if [ $TRANSMITIDO -gt 800 ]; then
        TRANSMITIDO=$(python -c "print(round($TRANSMITIDO/1024,2))")
        UNIDADTX="MB/s"
    else
        UNIDADTX="kB/s"
    fi

    echo "%{F$GREEN}$NET_DOWN $(printf "%4s" "$RECIBIDO") $UNIDADRX %{F$RED}$NET_UP $(printf "%4s" "$TRANSMITIDO") $UNIDADTX%{F-}"
}

fechahora()
{
    HORA=`date +%H:%M`
    #FECHA=`date +%d/%m/%y`
    FECHA=`date +%Y-%m-%d`
    echo -ne "%{A1:orage -t:}%{F$WHITE}$FECHA%{A}   %{F$MAIN}$RELOJ%{F-} %{F$WHITE}$HORA%{F-}"
}

tiempo()
{
    envsubst < ~/.lemonbar/weather_info
}

gmail()
{
    envsubst < ~/.lemonbar/gmail_notifications
}

while true; do
    echo "%{F-}%{l} $(ram) $(sep) $(temp)\
         %{B-}%{c}$(fechahora) \
         %{r}%{F-}$(gmail) $(sep) $(tiempo) $(sep) $(volumen) $(sep) $(musica) $(sep) $(discos) "
    sleep .5
done
