#!/bin/sh

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line; do
    case $line in
        D*)
            # clock
            sys="%{F$FG} ${line#?} %{F-}"
            ;;
        M*)
            # mpd
            mpd_status="%{F$FG} ${line#?} %{F-}"
            ;;
        F*)
            # disks
            disks="%{F$FG} ${line#?} %{F-}"
            ;;
        V*)
            # volume
            vol="%{F$FG} ${line#?} %{F-}"
            ;;
        R*)
            # ram
            ram="%{F$FG} ${line#?} %{F-}"
            ;;
        N*)
            # net
            net="%{F$FG} ${line#?} %{F-}"
            ;;
        B*)
            # battery
            bat="%{F$FG} ${line#?} %{F-}"
            ;;
        T*)
            # title
            title="%{F$WHITE} ${line#?} %{F-}"
            ;;
        W*)
            # bspwm
            wm=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ]; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        [ $num_mon -lt 2 ] && shift && continue
                        ;;
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free
                                F=$FG
                                B=$BG
                                ;;
                            F*)
                                # focused free
                                F=$FOCUS
                                B=$MAIN
                                ;;
                            o*)
                                # occupied
                                F=$WHITE
                                B=$BG
                                ;;
                            O*)
                                # focused occupied
                                F=$FOCUS
                                B=$MAIN
                                ;;
                            u*)
                                # urgent
                                F=$WHITE
                                B=$URGENT
                                ;;
                            U*)
                                # focused urgent
                                F=$WHITE
                                B=$URGENT
                                ;;
                        esac
                        wm="${wm}%{F$F}%{B$B}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm}%{c}${title}%{r}${net} ${bat} ${vol} ${sys}"
done
