alias p='sudo pacman'
alias pup='sudo pacman -Syu'
alias t='trizen'
alias tup='trizen -Syu'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'
alias winetricks32='WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks'
alias steam-wine='wine32 /mnt/extra/extra/wine32/drive_c/Program\ Files/Steam/Steam.exe -no-cef-sandbox'
alias steam-wine64='wine /mnt/extra/extra/wine32/drive_c/Program\ Files/Steam/Steam.exe -no-cef-sandbox'
alias d='sudo dnf -y'
alias di='sudo dnf -y install'
alias ds='dnf search'
alias du='sudo dnf update'
